### ISSUE TITLE
Cannot build project. PlatformIO reports that .sconsign39.dblite file or ESP32 folder is missing.

### ISSUE THREAD

**Issue by thomastech** [thomastech/PixelRadio#1]
**Problem:** 
Cannot build (compile) the PixelRadio project. PlatformIO reports that .sconsign39.dblite file or .pio\build\ESP32 folder is missing. Sometimes other unexpected errors occur during a build.

**Solution:**
PlatformIO Core 6.0 was recently released. Unfortunately this new release breaks the Platformio IDE and causes random build failures. More information is found here:
https://github.com/platformio/platformio-core/issues/4270

The workaround requires reverting back to the previous Core release (Core 5.2.5). If you experience this issue then please follow the instructions posted in the link.

The information discussed in the link says that the issue is solved by updating to the latest Core 6.0.1. But I found the build failures still occur, so please try Core 5.2.5 if the issue persists.

- Thomas

**Comment by thomastech** [comment]
Another possible solution to this issue is explained here:
https://github.com/platformio/platformio-core/issues/4286

- Thomas

**Comment by idorurez** [comment]
Have you been able to resolve this issue? This suddenly started happening to me as well.

None of the suggestions work for me (upgrade platformio, downgrade back to 5.2.5, blow away temp files). It does however work just once as soon as VS is loaded and intellisense finishes. After that, it gives me the same error.

**Comment by thomastech** [comment]
Still waiting for the PlatformIO devs to resolve this. Reverting back to 5.2.5 (and then delete the .pio folder) has been the workaround for me. Too bad it doesn't work for you, I don't have any other suggestions.

- Thomas

**Comment by thomastech** [comment]
Someone suggested removing the PlatformIO extension from VSCode and re-installing it. I haven't tried this, so if anyone has done it please report if it solved the problem.

- Thomas

**Comment by thomastech** [comment]
A new PlatformIO Core (version 6.0.2rc2) was released today. I can now build the project!

Details: https://github.com/platformio/platformio-core/issues/4286

@idorurez, please upgrade and let me know if you can successfully build.

- Thomas

**Comment by idorurez** [comment]
@thomastech I went through and blew away (aka backed-up) the packages/platform folders under ~/.platformio (sorry not at my home desk) and rebuilt. That seemed to do the job. I recalled I was working on a separate espidf platform and arduino component project and I must have goofed things up.

**Comment by thomastech** [comment]
@idorurez  Thanks for the update.  Glad to hear you are able to build the project.

It appears that the build problems are resolved with the new PlatformIO core release; Issue is Closed.

- Thomas

**Comment by thomastech** [comment]
Core 6.0.3 was released today. Tested, works OK.

- Thomas
