### ISSUE TITLE
Update to newest webserver v 3.0.0

### ISSUE THREAD

**Issue by jerryg-77** [thomastech/PixelRadio#6]
https://github.com/thomastech/PixelRadio/blob/6156d3821dd9c6456067a8acb2b2f7b21a9dba82/platformio.ini#L50

Change to:
https://github.com/esphome/ESPAsyncWebServer @ ^3.0.0 ; Updated lib, seems to have recent patches.

**Comment by thomastech** [comment]
Thanks for creating the issue ticket. Adding the updated library path is scheduled for the next PixelRadio release.

@all: In the meantime please manually edit the platformio.ini file as shown above.

**Comment by thomastech** [comment]
Source files have been updated and are available to download. The official V1.1.2 release will be available after *any* user confirms the project successfully builds and runs.

- Thomas

**Comment by thomastech** [comment]
Received confirmation that the V1.1.2 project builds and runs.
http://doityourselfchristmas.com/forums/showthread.php?58108-PixelRadio-a-DiY-FM-Transmitter-with-RDS-RadioText&p=552692#post552692

This ticket is closed.
