### ISSUE TITLE
Please include pick and place file

### ISSUE THREAD

**Issue by sslupsky** [thomastech/PixelRadio#7]
Could you please include the pick and place file for the board?  It would be possible to order an assembled board from JLCPCB if that is available.

**Comment by thomastech** [comment]
Attached is the CSV File. Created today, NOT validated, use at your own risk.

[Pick Place for PixelRadio.csv](https://github.com/thomastech/PixelRadio/files/10136341/Pick.Place.for.PixelRadio.csv)

Issue complete, closed ticket.

- Thomas

**Comment by sslupsky** [comment]
Thank you.

**Comment by sslupsky** [comment]
Apologies, one other thing I noticed, the parts list does not have the footprint.  Could you also please provide a BOM with the footprint?

**Comment by thomastech** [comment]
I'm unable to generate a useful footprint list for you without a lot of work on my end. So you'll have to create this on your own.

To get you started, attached is a basic BOM file you can use as a worksheet.

[PCB_Project_BOM.xls](https://github.com/thomastech/PixelRadio/files/10136786/PCB_Project_BOM.xls)

If JLCPCB has success with assembling your PixelRadio board then please come back and share all your files and any tips that might help the next project builder.

- Thomas

**Comment by sslupsky** [comment]
Thanks for the BOM.  I can pull most of what I need out of that.  One thing that would help is the lead spacing for the radial caps.

**Comment by thomastech** [comment]
The lead spacing measurements for many of the caps can be found in the big discussion at the doityourselfchristmas forum:
http://doityourselfchristmas.com/forums/showthread.php?58108-PixelRadio-a-DiY-FM-Transmitter-with-RDS-RadioText&p=549559#post549559

- Thomas

**Comment by sslupsky** [comment]
Now that you mention it I seem to recall that discussion in the forum thread.  I'll go review again.  I opened the gerbers in my viewer and had a closer look at the lead spacing of those components.

**Comment by sslupsky** [comment]
JLCPCB assembly looks like it will be about $50 for 5 boards.  Could save at least $2 per board I think if it was SMT.  This doesn't include the ESP32 or the RF module.

There are a few components that are difficult to source through JLCPCB/LCSC.  The thru hole inductors, the 1000pF and 220pF thru hole caps.

What is the voltage rating on C3?  I cannot find a capacitor with that footprint in a 16V rating.

Here is a screenshot of the JLC cost:
![Screen Shot 2022-12-02 at 5 52 28 PM](https://user-images.githubusercontent.com/16888734/205414317-13e6dc04-d82d-4a4d-8c57-d456d95bfeb9.png)


Let me know what you think.

**Comment by sslupsky** [comment]
One thing that would be helpful is if you could add two 15 pin female headers (for the MCU) to the PCB and regenerate the placement and BOM with these two additional components.

**Comment by sslupsky** [comment]
If we used SMT components I think component cost would come down as well.

**Comment by thomastech** [comment]
> JLCPCB assembly looks like it will be about $50 for 5 boards.

That is a good deal.

> What is the voltage rating on C3? I cannot find a capacitor with that footprint in a 16V rating.

Minimum C3 voltage is 6.3V. 

> Let me know what you think.

Some observations:

* Orientation of D1 is backwards in your screenshot.
* Double check C8 & C9 polarity. Hard to tell in the image but they look backwards to me.
* If you are using the recommended enclosure then LED1 should be hand-stuffed during final assembly so that it aligns with the hole in the front panel.

> One thing that would be helpful is if you could add two 15 pin female headers (for the MCU) to the PCB and regenerate the placement and BOM with these two additional components.

Sorry, you'll have to hand solder those.

> If we used SMT components I think component cost would come down as well.

Yes, for "production builds" an SMT layout would be important. But PixelRadio was released as a hobby project for home builders and through-hole was chosen to reduce the required soldering skills. In regards to home building, the FCC has a allowance for that activity. See Home-Built section: 
https://transition.fcc.gov/Bureaus/Engineering_Technology/Documents/bulletins/oet63/oet63rev.pdf

- Thomas

**Comment by sslupsky** [comment]
> Minimum C3 voltage is 6.3V.

Is there an ESR requirement for C2 ad C3?

> Some observations:
> 
> * Orientation of D1 is backwards in your screenshot.
> * Double check C8 & C9 polarity. Hard to tell in the image but they look backwards to me.
> * If you are using the recommended enclosure then LED1 should be hand-stuffed during final assembly so that it aligns with the hole in the front panel.

Yeah, I have to figure out how to "inform" JLCPCB about forming the leads for U2 and LED1 so they are placed properly.  I am not aware of how to do that.  Thanks for the feedback on the part orientation ... I overlooked the polarized caps.

> > One thing that would be helpful is if you could add two 15 pin female headers (for the MCU) to the PCB and regenerate the placement and BOM with these two additional components.
> 
> Sorry, you'll have to hand solder those.

I am not sure I was clear.  I am asking for the headers to be included in the BOM and placement files so the headers can be installed at JLCPCB.

> Yes, for "production builds" an SMT layout would be important. But PixelRadio was released as a hobby project for home builders and through-hole was chosen to reduce the required soldering skills. In regards to home building, the FCC has a allowance for that activity. See Home-Built section: https://transition.fcc.gov/Bureaus/Engineering_Technology/Documents/bulletins/oet63/oet63rev.pdf

I think I understand what you counsel here.  My interpretation is the hobbyist is required to assemble this transmitter by:

1. procurement of the carrier board, enclosure and modules,
2. insertion of the TTGO-T8 module,
3. hand soldering the RF module,
4. programming TTGO-T8 firmware,
5. assembly of enclosure,
6. jumper configuration,
7. attach antenna

The bulletin requires "their designers and builders are required to employ good engineering practices".  I think using JLCPCB assembly service helps to satisfy the "builders" part of this requirement, even more so than someone soldering one entirely from scratch.  You appear to have some significant experience in RF electronics.  So I believe this project meets the "designers" requirement as well.  So, I think the project meets the "home built" test.

**Comment by thomastech** [comment]
> Is there an ESR requirement for C2 ad C3?

ESR is not critical. But I suggest using low ESR that's recommended for power supply applications.

> I am asking for the headers to be included in the BOM and placement files so the headers can be installed at JLCPCB.

See attached file (added components HDR1-MCU1 and HDR2-MCU1):
[Pick Place for PixelRadio.csv](https://github.com/thomastech/PixelRadio/files/10147168/Pick.Place.for.PixelRadio.csv)

> I think I understand what you counsel here. My interpretation is the hobbyist is required to assemble this transmitter {snip}

I don't hold a law degree so I can't offer any useful regulatory advice. But my personal method is to be as conservative as practical and do all I can to avoid stepping on gov agency toes.

- Thomas

**Comment by sslupsky** [comment]
Are these inductors suitable?
https://www.bourns.com/docs/Product-Datasheets/78f_series.pdf

**Comment by sslupsky** [comment]
P2 and P3 coordinates appear to be a bit off.  Can you advise regarding the origin of these components?

U2 coordinates do not match the pcb either.

I fixed polarities on D1, C8 and C9.

Substituted a 25V cap for C3 to fit the footprint.  Perhaps a high capacitance cap would be a better sub?  Not sure what the spec for this pin on TTGO T8 is.

You have a connector installed for J8 shown in the assembly tips.  What connector did you use?

**Comment by sslupsky** [comment]
![capture-2022-12-03T21_07_57 355Z](https://user-images.githubusercontent.com/16888734/205462321-53e0e75a-478a-4933-bb3f-a1ce00460b7e.png)

**Comment by sslupsky** [comment]
I am having a hard time with the inductors (390nH, 10nH) and a few of the caps (1000pF and 220pF).  JLCPCB/LCSC has no stock on these.

**Comment by thomastech** [comment]
> Are these inductors suitable?
https://www.bourns.com/docs/Product-Datasheets/78f_series.pdf`

Those are OK.

> P2 and P3 coordinates appear to be a bit off. Can you advise regarding the origin of these components?
U2 coordinates do not match the pcb either.

Must be an error in the library. The best I can advise is the location of Pin 1.
P2-1 is center pad far left side, 4.659, 34.116 mm
P3-1 is center pad far left side, 5.334, 14.224 mm
U2-1 is first pad far left side, 48.514, 6.477 mm

> Substituted a 25V cap for C3 to fit the footprint. Perhaps a high capacitance cap would be a better sub?

25V rating is fine. Or feel free to use 220uF or 330uF if you must.

> You have a connector installed for J8 shown in the assembly tips. What connector did you use?

I did not design the board with any particular choice in mind. I merely grabbed a random JST that was in my parts bin.

> I am having a hard time with the inductors (390nH, 10nH) and a few of the caps (1000pF and 220pF). 

Those are all common values. Perhaps the inductors are listed in their equiv uH values. Caps can be listed in their equiv nF or uF values.

- Thomas

**Comment by sslupsky** [comment]
Updated pos of P2, P3 and U2.  Added JST XA header for J8.  Sub 470uF for C3 (used same value as the other caps to minimize number of diff parts).

Waiting for JLCPCB feedback regarding the lead forming.

![capture-2022-12-05T21_16_43 648Z](https://user-images.githubusercontent.com/16888734/205744931-32512f67-0fd2-4b6e-aa24-8da59934181e.png)

**Comment by thomastech** [comment]
Nice. You're on the home stretch.

> Waiting for JLCPCB feedback regarding the lead forming.

Perhaps also ask JLCPCB if they could install the jumper wire at the L7 location. Or check their parts inventory for 0-ohm jumper resistor.

- Thomas

**Comment by sslupsky** [comment]
Problem with the lead forming ... JLCPCB does not support that.  I'll see if they will ship the parts with the board so we can solder them.  I do not think they will though.

Good idea on the jumper.  I was looking all over for a wire jumper and did not think of a zero ohm axial resistor.

**Comment by sslupsky** [comment]
I am pretty sure the answer to this question is no but can I sub a 10uH inductor for the 390nH inductors?  I found a 10uH thru hole inductor at JLCPCB.

**Comment by thomastech** [comment]
> can I sub a 10uH inductor for the 390nH inductors? I found a 10uH thru hole inductor at JLCPCB.

Please use the original value (390nH).

- Thomas

**Comment by sslupsky** [comment]
I found a closer match to the 390nH inductor in stock.  It is 150nH.  That seems more suitable but may require an adjustment to the 1000pF capacitor used in the amplifier stage.  If we use the 150nH inductor and increase the 1000pF cap to 2700pF, would that be suitable?

The 10uH inductor may still be suitable for the audio input filtering.

**Comment by thomastech** [comment]
>  If we use the 150nH inductor and increase the 1000pF cap to 2700pF, would that be suitable?

Regarding the 390nH sub, 150nH is not recommended (will affect performance). And keep in mind that any changes to the RF PA will require a new RF validation to ensure conformity and performance.

> The 10uH inductor may still be suitable for the audio input filtering.

L1 and L2 are for RFI/EMI protection. Changing them to 10uH should be OK, but to prevent surprises be sure to measure audio bandwidth.

- Thomas

**Comment by kingofkristmas** [comment]
> I found a closer match to the 390nH inductor in stock. It is 150nH. That seems more suitable but may require an adjustment to the 1000pF capacitor used in the amplifier stage. If we use the 150nH inductor and increase the 1000pF cap to 2700pF, would that be suitable?
> 
> The 10uH inductor may still be suitable for the audio input filtering.

Any luck with JLCPCB? They seem to be short on a lot of components.

**Comment by thomastech** [comment]
Closed due to lack of activity.
